# Generated by Django 3.0.1 on 2019-12-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctacert',
            name='display_default',
            field=models.IntegerField(default=0, verbose_name='선택횟수'),
        ),
    ]
