# Generated by Django 3.0.1 on 2020-01-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nts', '0002_auto_20191231_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='NtsIdPw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentId', models.CharField(max_length=30, verbose_name='세무사관리번호')),
                ('agentPw', models.CharField(max_length=30, verbose_name='세무사비밀번호')),
                ('userId', models.CharField(max_length=30, verbose_name='사용자아이디')),
                ('userPw', models.CharField(max_length=30, verbose_name='사용자비밀번호')),
                ('use_cnt', models.IntegerField(default=0, verbose_name='사용횟수')),
                ('ctacert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nts.CtaCert')),
            ],
        ),
    ]
