# Generated by Django 3.0.1 on 2020-01-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nts', '0003_ntsidpw'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ntsidpw',
            unique_together={('userId', 'userPw')},
        ),
    ]
