# Generated by Django 3.0.1 on 2020-01-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nts', '0004_auto_20200101_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NtsIdPw',
            new_name='CtaIdPw',
        ),
    ]
